baseURL = "https://thetechtrap.com/"
languageCode = "en-us"
title = "The Tech Trap"
theme = "detox"
[params]
    description = "Free yourself from the tech trap"
[taxonomies]
   tag = "tags"
   category = "categories"